# Use postgres/example user/password credentials
version: '3.9'

services:

  db-cicd:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: azeqsd
      POSTGRES_USER: books
    ports:
      - "5432:5432"
    # env_file:
    #   - ./config/.env

volumes:
  postgres_data:

# docker-compose -f docker-compose-postgres-init.yml up -d