# Use postgres/example user/password credentials
version: '3.9'

services:

  db-cicd:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${CONTAINER_DB_PASSWORD}
      POSTGRES_USER: ${CONTAINER_DB_USER}
    env_file:
      - config/.env

volumes:
  postgres_data:

# docker-compose -f docker-compose-postgres-init.yml up